<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arquanix.Domain\Arquanix.Domain.csproj" />
    <ProjectReference Include="..\Arquanix.Infrastructure\Arquanix.Infrastructure.csproj" />
  </ItemGroup>

</Project>
